# Generated by Django 4.2.11 on 2024-04-18 18:07

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
    ]
