# Generated by Django 4.2.11 on 2024-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="name",
            field=models.CharField(default="public offer", max_length=100),
        ),
    ]
