# Generated by Django 4.2.11 on 2024-04-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="size",
            field=models.CharField(),
        ),
    ]
