# Generated by Django 4.2.11 on 2024-04-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_product_description"),
        ("cart", "0002_alter_cartitem_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("contact_info", models.JSONField()),
                ("delivery_info", models.JSONField()),
                ("delivery_method", models.CharField(max_length=50)),
                ("total_price", models.PositiveIntegerField(default=0)),
                ("products", models.ManyToManyField(to="shop.product")),
            ],
        ),
    ]
